Bug in Item3D::IsAboveBelow
JamesBremner/Pack pull request #8
Opened 2016-09-21 14:34 UTC by gustav21

When calculating `ol2` there must be `ol1` instead of `ow2`

2016-09-21 14:44 UTC, JamesBremner requested changes
This looks correct.  There is a unit test of IsAboveBelow().  Did the test miss this?  Can you add to the unit test so that the bug is caught?

2016-09-22 15:48 UTC, JamesBremner requested changes
Thank you.

This looks like you have modified the existing unit test.  Please do not do that!  If you add a new test specifically for the bug you found, then everything will be clear and any bugs the existing test was designed to detect will still be tested.

2016-09-23 06:48 UTC, gustav21 commented
Ok, sorry, I'll try to add new test for the bug.

2016-09-23 19:03 UTC, JamesBremner approved these changes
Thank you

2016-09-23 19:03 UTC, merged